#!/bin/sh

dotfiles_do() {
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

dotfiles_do pull

# Refresh workflow
$HOME/workflow-sync

# Reset finder
killall cfprefsd
killall Finder

# Reset shell and source
exec $SHELL && source $HOME/.zshrc
