#!/bin/sh

dotfiles_do() {
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

dotfiles_do pull

# Refresh workflow
$HOME/workflow-sync

# Brew
brew update

# Update vim plugins
vim +PluginInstall +qall

killall cfprefsd
killall Finder
