#!/bin/sh

if [ -f "$HOME/.workflow/shortcuts/shortcuts.local" ]; then
  defaults write -g NSUserKeyEquivalents "{$(cat shortcuts shortcuts.local)}"
else
  defaults write -g NSUserKeyEquivalents "{$(cat shortcuts)}"
fi


